---
- name: Update and patch Ubuntu nodes
  hosts: kubernetes
  become: yes
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      register: update_result

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
      when: update_result.changed # Only run if cache was updated

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the node if required
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists
