network:
  ethernets: {}
  version: 2
  # Wifi configuration
  wifis:
    # The Wi-Fi network interface of your homelab machine
    wlo1:
      access-points:
        # Replace with the name of your Wi-Fi home network SSID
        YourAccessPointName:
          # Update with the Wi-Fi password for your home network
          password: YourWifiPassword
      # Use static IP addresses
      dhcp4: false
      # The static IP address you want to use for this machine
      addresses: [192.168.1.101/24]
      nameservers:
        # The list of DNS servers you want to use for this machine
        # Typically this will be your router's IP address, and you
        # can add Google's public DNS servers as backups
        addresses: [192.168.1.1, 8.8.8.8, 8.8.4.4]
      routes:
        - to: default
          # This must be your default gateway for the Wi-Fi network
          via: 192.168.1.1
